name: test

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}

      - name: Cache Android Gems
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Flutter get
        working-directory: ${{ github.workspace }}
        run: flutter pub get

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > ${{ github.workspace }}/android/app.jks

      - name: Set up key.properties
        working-directory: ${{ github.workspace }}
        run: |
          echo keyPassword=\${{ secrets.SIGNING_STORE_PASSWORD }} > ${{ env.PROPERTIES_PATH }}
          echo storePassword=\${{ secrets.SIGNING_KEY_PASSWORD }} >> ${{ env.PROPERTIES_PATH }}
          echo keyAlias=\${{ secrets.SIGNING_KEY_ALIAS }} >> ${{ env.PROPERTIES_PATH }}
        env:
          PROPERTIES_PATH: "${{ github.workspace }}/android/key.properties"

      - name: Build APK
        if: github.event_name == 'push'
        working-directory: ${{ github.workspace }}
        run: flutter build apk

      - name: Create Firebase Service Credentials file
        run: |
          echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json.b64
          base64 -d -i firebase_credentials.json.b64 > "${{ github.workspace }}/android/firebase_credentials.json"
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}

      - name: Distribute Android Beta App
        if: github.event_name == 'push'
        working-directory: ${{ github.workspace }}/android
        run: bundle exec fastlane android deploy_to_firebase
        env:
          FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
